### ISSUE TITLE
The i-bus port is mislabeled on the x6b

### ISSUE THREAD

**Issue by LevinGermann** [upinthesky/upinthesky.github.io#1]
Hello,

First of all - thanks for the amazing page. It really helped me out when connecting my Eaching Wizard x220s to the Flysky x6b receiver.
Unfortunately I spent many hours figuring out why my receiver wasn't working; until I found out that I plugged the connector in the PPM connector instead of the i-bus connector.

https://upinthesky.github.io/2017/10/23/eachine-wizard-x220s-arf-overview-and-receiver-installation.html

The image [x6b.png](https://upinthesky.github.io/images/eachine_wizard_x220s_arf_overview_and_receiver_installation/x6b.png) states that the connector on the right is the i-bus connector, but in reality it's the one on the left. (See [here](https://image.getfpv.com/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/r/m/rm7985-1-9c57-lnmj.jpg))

Best regards

**Comment by upinthesky** [comment]
Hi,

thanks for spotting this.
Issue solved.
