### ISSUE TITLE
Regarding receiver on iFlight Nazgul 5

### ISSUE THREAD

**Issue by SecGus** [upinthesky/upinthesky.github.io#2]
Hello, 

Sorry to post this on the actual github as an issue, not sure how else to contact you, and I hope you don't mind me asking a question so directly.

I purchased the iFlight Nazgul 5 although I have a flysky controller. I bought the drone without a receiver and saw your mention of the Flysky X6B. I have been looking all over for a valid receiver to talk to my Flysky-I6X, and have been struggling to make the other receiver I have (an FS-A8S) talk to the nazgul due to incompatibility between connectors.

How would you recommend I connect the nazgul 5 to the X6B? What is the easiest / simplest way?

Apologies in advance if I am being a bit brief with the topic, I am fairly new to drone piloting and am not sure what the best way to connect an FS-A8S or an FS-X6B with the nazgul ESC (https://uk.banggood.com/IFlight-SucceX-E-F405-F4-Flight-Controller-2-6S-5V3A-BEC-30_5x30_5mm-p-1553341.html?cur_warehouse=CN).

Thank you in advance.

**Comment by upinthesky** [comment]
Hi,

you can take a look at this video which explains in detail the steps to connect correctly FlySky receivers to iFlight SucceX-E F4 FC: https://www.youtube.com/watch?v=5dQMmTc_QOs&feature=emb_logo
